package compare

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/Korrnals/gotr/internal/client"
	"github.com/Korrnals/gotr/internal/parallel"
	"github.com/Korrnals/gotr/internal/ui"
	"github.com/Korrnals/gotr/internal/utils"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var retryFailedPagesCmd = newRetryFailedPagesCmd()

type failedPagesFile struct {
	GeneratedAt string                `json:"generated_at"`
	Total       int                   `json:"total"`
	FailedPages []parallel.FailedPage `json:"failed_pages"`
}

type retryFailedPagesOptions struct {
	Attempts int
	Workers  int
	Delay    time.Duration
}

type retryFailedPagesStats struct {
	InputPages      int
	UniquePages     int
	RecoveredPages  int
	RecoveredCases  int
	RemainingPages  int
	SaveRemainingTo string
}

func newRetryFailedPagesCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "retry-failed-pages",
		Short: "Точечный ретрай непрогруженных страниц кейсов",
		Long: `Читает JSON-отчёт непрогруженных страниц (generated by compare cases)
и пытается догрузить только эти страницы, без полного повторного прогона.

Примеры:
	gotr compare retry-failed-pages --from ~/.gotr/exports/compare/failed_pages_2026-03-03_10-15-00.json
	gotr compare retry-failed-pages --from failed.json --attempts 3 --workers 8
	gotr compare retry-failed-pages --from failed.json --save-remaining /tmp/failed_remaining.json
`,
		RunE: runRetryFailedPages,
	}

	cmd.Flags().String("from", "", "Путь к JSON-отчёту с failed pages (обязательно)")
	cmd.Flags().Int("attempts", 3, "Количество попыток для каждой страницы")
	cmd.Flags().Int("workers", 6, "Параллельных воркеров для точечного ретрая")
	cmd.Flags().Duration("retry-delay", 500*time.Millisecond, "Пауза между попытками одной страницы")
	cmd.Flags().String("save-remaining", "", "Куда сохранить оставшиеся непрогруженные страницы (JSON). Если не указан — автосохранение в ~/.gotr/exports/compare/")

	return cmd
}

func runRetryFailedPages(cmd *cobra.Command, _ []string) error {
	cli := getClientSafe(cmd)
	if cli == nil {
		return fmt.Errorf("HTTP клиент не инициализирован")
	}

	fromPath, _ := cmd.Flags().GetString("from")
	saveRemainingPath, _ := cmd.Flags().GetString("save-remaining")

	if strings.TrimSpace(fromPath) == "" {
		return fmt.Errorf("флаг --from обязателен")
	}

	failedPages, err := loadFailedPages(fromPath)
	if err != nil {
		return err
	}

	resolvedOpts, err := resolveRetryFailedPagesOptionsFromConfig(cmd)
	if err != nil {
		return err
	}

	_, _, err = executeRetryFailedPages(cli, failedPages, resolvedOpts, fromPath, saveRemainingPath)
	return err
}

func resolveRetryFailedPagesOptionsFromConfig(cmd *cobra.Command) (retryFailedPagesOptions, error) {
	overrides := map[string]any{}

	if flag := cmd.Flags().Lookup("attempts"); flag != nil && flag.Changed {
		value, _ := cmd.Flags().GetInt("attempts")
		overrides["retry_attempts"] = value
	}
	if flag := cmd.Flags().Lookup("workers"); flag != nil && flag.Changed {
		value, _ := cmd.Flags().GetInt("workers")
		overrides["retry_workers"] = value
	}
	if flag := cmd.Flags().Lookup("retry-delay"); flag != nil && flag.Changed {
		value, _ := cmd.Flags().GetDuration("retry-delay")
		overrides["retry_delay"] = value
	}

	runtimeConfig, err := resolveCompareCasesRuntimeConfig(overrides, viper.GetString("base_url"))
	if err != nil {
		return retryFailedPagesOptions{}, err
	}

	return retryFailedPagesOptions{
		Attempts: runtimeConfig.RetryAttempts,
		Workers:  runtimeConfig.RetryWorkers,
		Delay:    runtimeConfig.RetryDelay,
	}, nil
}

func executeRetryFailedPages(
	cli client.ClientInterface,
	failedPages []parallel.FailedPage,
	opts retryFailedPagesOptions,
	sourceLabel string,
	saveRemainingPath string,
) ([]parallel.FailedPage, retryFailedPagesStats, error) {
	if len(failedPages) == 0 {
		if sourceLabel != "" {
			ui.Successf(os.Stderr, "Нет непрогруженных страниц: %s", sourceLabel)
		}
		return nil, retryFailedPagesStats{}, nil
	}

	if opts.Attempts <= 0 {
		opts.Attempts = 1
	}
	if opts.Workers <= 0 {
		opts.Workers = 1
	}
	if opts.Delay < 0 {
		opts.Delay = 0
	}

	uniquePages := dedupeFailedPages(failedPages)
	stats := retryFailedPagesStats{
		InputPages:  len(failedPages),
		UniquePages: len(uniquePages),
	}
	ui.Section(os.Stderr, "Точечный ретрай failed pages")
	if sourceLabel != "" {
		ui.Infof(os.Stderr, "Источник: %s", sourceLabel)
	}
	ui.Infof(os.Stderr, "Страниц в отчёте: %d (уникальных: %d)", len(failedPages), len(uniquePages))
	ui.Infof(os.Stderr, "Параметры: attempts=%d, workers=%d, retry-delay=%s", opts.Attempts, opts.Workers, opts.Delay)

	type retryResult struct {
		page  parallel.FailedPage
		err   error
		count int
	}

	jobs := make(chan parallel.FailedPage, len(uniquePages))
	results := make(chan retryResult, len(uniquePages))

	for _, page := range uniquePages {
		jobs <- page
	}
	close(jobs)

	for i := 0; i < opts.Workers; i++ {
		go func() {
			for page := range jobs {
				var lastErr error
				var fetched int

				for attempt := 1; attempt <= opts.Attempts; attempt++ {
					cases, err := cli.GetCasesPage(page.ProjectID, page.SuiteID, page.Offset, page.Limit)
					if err == nil {
						fetched = len(cases)
						lastErr = nil
						break
					}
					lastErr = err
					if attempt < opts.Attempts && opts.Delay > 0 {
						time.Sleep(opts.Delay)
					}
				}

				results <- retryResult{page: page, err: lastErr, count: fetched}
			}
		}()
	}

	remaining := make([]parallel.FailedPage, 0)
	recoveredPages := 0
	recoveredCases := 0

	for i := 0; i < len(uniquePages); i++ {
		result := <-results
		if result.err != nil {
			result.page.Error = result.err.Error()
			remaining = append(remaining, result.page)
			continue
		}
		recoveredPages++
		recoveredCases += result.count
	}

	sort.Slice(remaining, func(i, j int) bool {
		a := remaining[i]
		b := remaining[j]
		if a.ProjectID != b.ProjectID {
			return a.ProjectID < b.ProjectID
		}
		if a.SuiteID != b.SuiteID {
			return a.SuiteID < b.SuiteID
		}
		if a.Offset != b.Offset {
			return a.Offset < b.Offset
		}
		return a.Limit < b.Limit
	})

	ui.Stat(os.Stderr, "✅", "Восстановлено страниц", fmt.Sprintf("%d/%d", recoveredPages, len(uniquePages)))
	ui.Stat(os.Stderr, "📦", "Получено кейсов из ретрая", fmt.Sprintf("%d", recoveredCases))
	stats.RecoveredPages = recoveredPages
	stats.RecoveredCases = recoveredCases
	stats.RemainingPages = len(remaining)
	if len(remaining) == 0 {
		ui.Successf(os.Stderr, "Все проблемные страницы успешно догружены")
		return nil, stats, nil
	}

	ui.Warningf(os.Stderr, "Осталось непрогруженных страниц: %d", len(remaining))
	showLimit := 10
	if len(remaining) < showLimit {
		showLimit = len(remaining)
	}
	for i := 0; i < showLimit; i++ {
		fp := remaining[i]
		ui.Infof(os.Stderr, "  - проект=%d suite=%d page=%d offset=%d limit=%d", fp.ProjectID, fp.SuiteID, fp.PageNum, fp.Offset, fp.Limit)
	}
	if len(remaining) > showLimit {
		ui.Infof(os.Stderr, "  ... и ещё %d страниц", len(remaining)-showLimit)
	}

	reportPath, saveErr := saveFailedPagesReport(remaining, saveRemainingPath)
	if saveErr != nil {
		return remaining, stats, fmt.Errorf("ошибка сохранения остатка failed pages: %w", saveErr)
	}
	stats.SaveRemainingTo = reportPath
	ui.Infof(os.Stderr, "Остаток failed pages сохранён: %s", reportPath)

	return remaining, stats, nil
}

func loadFailedPages(path string) ([]parallel.FailedPage, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("не удалось прочитать файл %s: %w", path, err)
	}

	var report failedPagesFile
	if err := json.Unmarshal(data, &report); err != nil {
		return nil, fmt.Errorf("не удалось распарсить JSON отчёт %s: %w", path, err)
	}

	if report.FailedPages == nil {
		return []parallel.FailedPage{}, nil
	}
	return report.FailedPages, nil
}

func dedupeFailedPages(pages []parallel.FailedPage) []parallel.FailedPage {
	if len(pages) == 0 {
		return pages
	}

	unique := make([]parallel.FailedPage, 0, len(pages))
	seen := make(map[string]struct{}, len(pages))

	for _, page := range pages {
		key := fmt.Sprintf("%d:%d:%d:%d", page.ProjectID, page.SuiteID, page.Offset, page.Limit)
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		if page.PageNum <= 0 && page.Limit > 0 {
			page.PageNum = page.Offset/page.Limit + 1
		}
		unique = append(unique, page)
	}

	utils.DebugPrint("[RetryFailedPages] dedupe: %d -> %d", len(pages), len(unique))
	return unique
}
