package compare

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/Korrnals/gotr/internal/client"
	"github.com/Korrnals/gotr/internal/concurrency"
	"github.com/Korrnals/gotr/internal/debug"
	"github.com/Korrnals/gotr/internal/ui"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var retryFailedPagesCmd = newRetryFailedPagesCmd()

// failedPagesFile describes the persisted failed-pages retry report format.
type failedPagesFile struct {
	GeneratedAt string             `json:"generated_at"`
	Total       int                `json:"total"`
	FailedPages []failedPageRecord `json:"failed_pages"`
}

// failedPageRecord is a command-level DTO used for report persistence.
type failedPageRecord struct {
	ProjectID int64  `json:"project_id"`
	SuiteID   int64  `json:"suite_id"`
	Offset    int    `json:"offset"`
	Limit     int    `json:"limit"`
	PageNum   int    `json:"page_num"`
	Error     string `json:"error,omitempty"`
}

func (r failedPageRecord) toFailedPage() concurrency.FailedPage {
	return concurrency.FailedPage{
		ProjectID: r.ProjectID,
		SuiteID:   r.SuiteID,
		Offset:    r.Offset,
		Limit:     r.Limit,
		PageNum:   r.PageNum,
		Error:     r.Error,
	}
}

// retryFailedPagesOptions contains runtime retry knobs for a targeted retry run.
type retryFailedPagesOptions struct {
	Attempts int
	Workers  int
	Delay    time.Duration
}

// retryFailedPagesStats contains summary metrics produced by retry execution.
type retryFailedPagesStats struct {
	InputPages      int
	UniquePages     int
	RecoveredPages  int
	RecoveredCases  int
	RemainingPages  int
	SaveRemainingTo string
}

// newRetryFailedPagesCmd creates the targeted retry command for failed pages.
func newRetryFailedPagesCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "retry-failed-pages",
		Short: "Retry only failed case pages from a report",
		Long: `Reads a JSON report with failed pages (generated by compare cases)
and retries loading only those pages without rerunning the full compare.

Examples:
	gotr compare retry-failed-pages --from ~/.gotr/exports/compare/failed_pages_2026-03-03_10-15-00.json
	gotr compare retry-failed-pages --from failed.json --attempts 3 --workers 8
	gotr compare retry-failed-pages --from failed.json --save-remaining /tmp/failed_remaining.json
`,
		RunE: runRetryFailedPages,
	}

	cmd.Flags().String("from", "", "Path to a JSON report with failed pages (required)")
	cmd.Flags().Int("attempts", 3, "Retry attempts per page")
	cmd.Flags().Int("workers", 6, "Parallel workers for targeted retry")
	cmd.Flags().Duration("retry-delay", 500*time.Millisecond, "Delay between attempts for one page")
	cmd.Flags().String("save-remaining", "", "Where to save remaining failed pages (JSON). If empty, auto-save to ~/.gotr/exports/compare/")

	return cmd
}

// runRetryFailedPages executes the retry-failed-pages command flow.
func runRetryFailedPages(cmd *cobra.Command, _ []string) error {
	cli := getClientSafe(cmd)
	ctx := cmd.Context()
	if cli == nil {
		return fmt.Errorf("HTTP client not initialized")
	}

	fromPath, _ := cmd.Flags().GetString("from")
	saveRemainingPath, _ := cmd.Flags().GetString("save-remaining")

	if strings.TrimSpace(fromPath) == "" {
		return fmt.Errorf("--from flag is required")
	}

	failedPages, err := loadFailedPages(fromPath)
	if err != nil {
		return err
	}

	resolvedOpts, err := resolveRetryFailedPagesOptionsFromConfig(cmd)
	if err != nil {
		return err
	}

	_, _, err = executeRetryFailedPages(ctx, cli, failedPages, resolvedOpts, fromPath, saveRemainingPath)
	return err
}

// resolveRetryFailedPagesOptionsFromConfig merges flags with compare retry config defaults.
func resolveRetryFailedPagesOptionsFromConfig(cmd *cobra.Command) (retryFailedPagesOptions, error) {
	overrides := map[string]any{}

	if flag := cmd.Flags().Lookup("attempts"); flag != nil && flag.Changed {
		value, _ := cmd.Flags().GetInt("attempts")
		overrides["retry_attempts"] = value
	}
	if flag := cmd.Flags().Lookup("workers"); flag != nil && flag.Changed {
		value, _ := cmd.Flags().GetInt("workers")
		overrides["retry_workers"] = value
	}
	if flag := cmd.Flags().Lookup("retry-delay"); flag != nil && flag.Changed {
		value, _ := cmd.Flags().GetDuration("retry-delay")
		overrides["retry_delay"] = value
	}

	runtimeConfig, err := resolveCompareCasesRuntimeConfig(overrides, viper.GetString("base_url"))
	if err != nil {
		return retryFailedPagesOptions{}, err
	}

	return retryFailedPagesOptions{
		Attempts: runtimeConfig.RetryAttempts,
		Workers:  runtimeConfig.RetryWorkers,
		Delay:    runtimeConfig.RetryDelay,
	}, nil
}

// executeRetryFailedPages retries each unique failed page and returns remaining failures.
func executeRetryFailedPages(
	ctx context.Context,
	cli client.ClientInterface,
	failedPages []concurrency.FailedPage,
	opts retryFailedPagesOptions,
	sourceLabel string,
	saveRemainingPath string,
) ([]concurrency.FailedPage, retryFailedPagesStats, error) {
	if len(failedPages) == 0 {
		if sourceLabel != "" {
			ui.Successf(os.Stderr, "No failed pages to retry: %s", sourceLabel)
		}
		return nil, retryFailedPagesStats{}, nil
	}

	if opts.Attempts <= 0 {
		opts.Attempts = 1
	}
	if opts.Workers <= 0 {
		opts.Workers = 1
	}
	if opts.Delay < 0 {
		opts.Delay = 0
	}

	uniquePages := dedupeFailedPages(failedPages)
	stats := retryFailedPagesStats{
		InputPages:  len(failedPages),
		UniquePages: len(uniquePages),
	}
	ui.Section(os.Stderr, "Targeted failed pages retry")
	if sourceLabel != "" {
		ui.Infof(os.Stderr, "Source: %s", sourceLabel)
	}
	ui.Infof(os.Stderr, "Pages in report: %d (unique: %d)", len(failedPages), len(uniquePages))
	ui.Infof(os.Stderr, "Parameters: attempts=%d, workers=%d, retry-delay=%s", opts.Attempts, opts.Workers, opts.Delay)

	type retryResult struct {
		page  concurrency.FailedPage
		err   error
		count int
	}

	jobs := make(chan concurrency.FailedPage, len(uniquePages))
	results := make(chan retryResult, len(uniquePages))

	for _, page := range uniquePages {
		jobs <- page
	}
	close(jobs)

	for i := 0; i < opts.Workers; i++ {
		go func() {
			for page := range jobs {
				var lastErr error
				var fetched int

				for attempt := 1; attempt <= opts.Attempts; attempt++ {
					cases, err := cli.GetCasesPage(ctx, page.ProjectID, page.SuiteID, page.Offset, page.Limit)
					if err == nil {
						fetched = len(cases)
						lastErr = nil
						break
					}
					lastErr = err
					if attempt < opts.Attempts && opts.Delay > 0 {
						time.Sleep(opts.Delay)
					}
				}

				results <- retryResult{page: page, err: lastErr, count: fetched}
			}
		}()
	}

	remaining := make([]concurrency.FailedPage, 0)
	recoveredPages := 0
	recoveredCases := 0

	for i := 0; i < len(uniquePages); i++ {
		result := <-results
		if result.err != nil {
			result.page.Error = result.err.Error()
			remaining = append(remaining, result.page)
			continue
		}
		recoveredPages++
		recoveredCases += result.count
	}

	sort.Slice(remaining, func(i, j int) bool {
		a := remaining[i]
		b := remaining[j]
		if a.ProjectID != b.ProjectID {
			return a.ProjectID < b.ProjectID
		}
		if a.SuiteID != b.SuiteID {
			return a.SuiteID < b.SuiteID
		}
		if a.Offset != b.Offset {
			return a.Offset < b.Offset
		}
		return a.Limit < b.Limit
	})

	ui.Stat(os.Stderr, "OK", "Recovered pages", fmt.Sprintf("%d/%d", recoveredPages, len(uniquePages)))
	ui.Stat(os.Stderr, "INFO", "Cases fetched by retry", fmt.Sprintf("%d", recoveredCases))
	stats.RecoveredPages = recoveredPages
	stats.RecoveredCases = recoveredCases
	stats.RemainingPages = len(remaining)
	if len(remaining) == 0 {
		ui.Successf(os.Stderr, "All failed pages were recovered successfully")
		return nil, stats, nil
	}

	ui.Warningf(os.Stderr, "Failed pages still remaining: %d", len(remaining))
	showLimit := 10
	if len(remaining) < showLimit {
		showLimit = len(remaining)
	}
	for i := 0; i < showLimit; i++ {
		fp := remaining[i]
		ui.Infof(os.Stderr, "  - project=%d suite=%d page=%d offset=%d limit=%d", fp.ProjectID, fp.SuiteID, fp.PageNum, fp.Offset, fp.Limit)
	}
	if len(remaining) > showLimit {
		ui.Infof(os.Stderr, "  ... and %d more pages", len(remaining)-showLimit)
	}

	reportPath, saveErr := saveFailedPagesReport(remaining, saveRemainingPath)
	if saveErr != nil {
		return remaining, stats, fmt.Errorf("save remaining failed pages error: %w", saveErr)
	}
	stats.SaveRemainingTo = reportPath
	ui.Infof(os.Stderr, "Remaining failed pages saved to: %s", reportPath)

	return remaining, stats, nil
}

// loadFailedPages reads and parses a failed-pages report file.
func loadFailedPages(path string) ([]concurrency.FailedPage, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read file %s: %w", path, err)
	}

	var report failedPagesFile
	if err := json.Unmarshal(data, &report); err != nil {
		return nil, fmt.Errorf("failed to parse JSON report %s: %w", path, err)
	}

	if report.FailedPages == nil {
		return []concurrency.FailedPage{}, nil
	}

	pages := make([]concurrency.FailedPage, 0, len(report.FailedPages))
	for _, rec := range report.FailedPages {
		pages = append(pages, rec.toFailedPage())
	}

	return pages, nil
}

// dedupeFailedPages removes duplicate page descriptors while preserving order.
func dedupeFailedPages(pages []concurrency.FailedPage) []concurrency.FailedPage {
	if len(pages) == 0 {
		return pages
	}

	unique := make([]concurrency.FailedPage, 0, len(pages))
	seen := make(map[string]struct{}, len(pages))

	for _, page := range pages {
		key := fmt.Sprintf("%d:%d:%d:%d", page.ProjectID, page.SuiteID, page.Offset, page.Limit)
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		if page.PageNum <= 0 && page.Limit > 0 {
			page.PageNum = page.Offset/page.Limit + 1
		}
		unique = append(unique, page)
	}

	debug.DebugPrint("[RetryFailedPages] dedupe: %d -> %d", len(pages), len(unique))
	return unique
}
